### ISSUE TITLE
Suggestions for Knulli theme

### ISSUE THREAD

**Issue by rogs123** [symbuzzer/es-theme-knulli#3]
Hi - I love the simplicity and speed of the Knulli theme on Batocera - thank you for putting it together. If you're open to suggestions, I have a few:

1/ Add aleck64 and alice32 as systems (there are relevant png files in the ckau-book theme).
2/ Add a variant for no animation or reflection for the system view.
3/ Add a "Grid (no video)" variant.
4/ Add a "no-XML" variant to Detailed with just the boxart and video. This is similar to one of the views in art-book-next but it's super clean and easier to navigate sometimes when you have a large library.

That's it! Thank you.

**Comment by symbuzzer** [comment]
Thanks for your suggestions. I will try to add all on next release

**Comment by symbuzzer** [comment]
@rogs123 Can u test latest [v2.2.0](https://github.com/symbuzzer/es-theme-knulli/releases/tag/v2.2.0) and report please?
If u are using knulli, u can use [ETK Tool](https://github.com/symbuzzer/etk_tool)

**Comment by rogs123** [comment]
Hey - this is looking good - thank you!

Added disable video option for all gamelist views - **Works great in Grid mode - see below for issue with Detailed.**
Added disable system animations and reflection option - **Works**
Added missing aleck64 and alice32 system logos - **Works - thank you.**

Added new detailed_2 view - couple of issues with this one:

1/ With the disable video option - the box art does not show up at all in the Detailed and Detailed_2 views.

2/ For Detailed_2 (no xml), I was thinking that you would have the marquee with the box art below which transitions to video if enabled. Terrible mockups here:

![detailed_2 - no xml 2](https://github.com/user-attachments/assets/b3eb8a42-bc9c-4fce-b3ed-46fc986f4437)
![detailed_2 - no xml 1](https://github.com/user-attachments/assets/61dcc265-cb01-4835-a3d7-9bbb6c043945)

**Comment by symbuzzer** [comment]
Sorry I uploaded new v2.2.0
Can u reinstall and try it please?
@rogs123

**Comment by rogs123** [comment]
Yep - just tried new 2.2.0. Same issue if video is disabled - box art does not show at all in Detailed or Detailed_2.

XML is removed from Detailed_2 - was looking to see if you could increase the size of the box art to more fill the right window.

**Comment by symbuzzer** [comment]
@rogs123  I cant reproduce your issues

This is video enabled on detailed:
![{85057A4A-1D77-4DB3-B630-1AB579B1F009}](https://github.com/user-attachments/assets/2f3b4f23-c230-4907-88bd-289db2653634)

This is video disabled on detailed:
![{104F9381-0450-40E5-8650-666010CB8E18}](https://github.com/user-attachments/assets/c3a1d0e5-9e30-4d7e-85a6-f2c0c4bc59c8)

This is video enabled on detailed_2:
![{7EE54E48-1A81-4A1A-9DA9-F883A4097968}](https://github.com/user-attachments/assets/5803dc08-2967-4eb0-9a19-b8dbbf18c236)

This is video disabled on detailed_2:
![{D0C71510-A926-41E7-8787-8E74FED387EF}](https://github.com/user-attachments/assets/a911e7f7-9d11-491c-a238-02be526a04a4)

**Comment by rogs123** [comment]
Ok - will take another look today.

**Comment by symbuzzer** [comment]
> Ok - will take another look today.

Please check your scrapper settings and make sure you are scraping boxart

**Comment by rogs123** [comment]
ah yeah - makes sense. I'm using <image> for boxart - so what you have implemented is correct. If I change the md_boxart to md_thumbnail for detailed and detailed_2 - that works as expected.

**Comment by symbuzzer** [comment]
What can you do suggest me for fixing this?

**Comment by rogs123** [comment]
I think <image ifSubset="disableVideos:yes" name="md_thumbnail" is the way to go since you're using thumbnail in the grid view? I'm not a theme expert at all so please take my guidance with a pinch of salt :)

**Comment by symbuzzer** [comment]
I will try your suggestion. Also found some issues with detailed_2. Will update v2.2.0 beta tomorrow again. Will ping you. Thanks for your effort

**Comment by symbuzzer** [comment]
@rogs123 can u try latest 2.2.0 sir?
with clean install

**Comment by rogs123** [comment]
Hi @symbuzzer I downloaded the latest from here: https://github.com/symbuzzer/es-theme-knulli/releases/tag/v2.2.0

All works great! No issues.

**Comment by symbuzzer** [comment]
@rogs123 Thanks for your suggestions and testing

**Comment by symbuzzer** [comment]
Please remove and install latest stable v2.2.0 https://github.com/symbuzzer/es-theme-knulli/archive/refs/heads/main.zip
It has a lot of changes from beta which you installed.
Also see README.md for suggested ScreenScraper settings
